[package]
name = "bookily"
version = "0.1.0"
authors = ["cesasol", "Mathieu Aucejo"]
license = "MIT"
description = "Typst template for traditional book publishing (fork of bookly)"
entrypoint = "src/bookily.typ"
categories = ["book", "model"]
repository = "https://github.com/cesasol/bookily"
exclude = ["docs/manual.pdf"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnails/main.png"